language: java

jdk:
  - openjdk14

env:
  global:
    - CODECOV_TOKEN="f83f1895-a3d3-43c9-ac40-e89b133a851b"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - anton.starichenkov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
